version: '3.4'

services:
  redisdb:
    image: redis:alpine

  sqlserver1:
    image: mcr.microsoft.com/mssql/server

  storeapi:
    image: ${DOCKER_REGISTRY-}storeapi
    build:
      context: .
      dockerfile: Store-Api/Dockerfile
