version: '3.4'

services:
  redisdb:
    container_name: redisdb
    restart: always
    ports:
      - "6379:6379"

  sqlserver1:
    container_name: sqlserver1
    environment:
      SA_PASSWORD: "Sa@123456"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  storeapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - sqlserver1
      - redisdb
    ports:
      - "9191:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
